# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.6'  # Or minimum iOS version supported
prepare_react_native_project!

 

use_frameworks! :linkage => :static 

 

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

target 'TamarCosmetics' do
  config = use_native_modules!

   pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TamarCosmeticsTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

target 'OneSignalNotificationServiceExtension' do
  platform :ios, '15.6'
  use_frameworks! :linkage => :static

  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end